blank_issues_enabled: false
contact_links:
  - name: ğŸ™ Integrazione Originale (Octopus Energy IT)
    url: https://github.com/samuelebistoletti/HomeAssistant-OctopusEnergyIT
    about: Visita l'integrazione originale da cui Ã¨ stato preso spunto.
